### ISSUE TITLE
not sending the full list of coins in the telegram bot chat

### ISSUE THREAD

**Issue by mshaltaf** [cyberjunky/3commas-cyber-bots#135]
**Describe the bug**
not sending the full list of coins in the telegram bot chat as below :

Bot '2263878' with id '7099258' updated with 10 pairs (USDT_DCR ... USDT_WOO)

plaese advise if we can change this to show all the selected coins 

altrank is the used bot 

thanks

**Comment by amargedon** [comment]
This is as designed, actually. In one of the first versions, we send the complete list which is ok when using 10 pairs. When, however, you are using 100 (or even more) pairs this list becomes huges and unreable. Even to a point where apprise will not deliver the message anymore because it's length is too long. So that is why only the first and last pair is shown.

In the logging you can find the complete list. Also the bot will, of course, have the complete list.

Does that give enough access to the complete list of pairs?

**Comment by cyberjunky** [comment]
Stale ticket, closing, please (re)open if needed.
