### ISSUE TITLE
Cyberbot assistant on new platform (better than 3c)

### ISSUE THREAD

**Issue by dangalv** [cyberjunky/3commas-cyber-bots#197]
Greetings!
I'm opening the thread just to mention that there is a new platform that, in my point of view, is better and has more functions than 3c.
I hope you consider developing something similar to this magnificent assistant.

new platform:
**_gainium.io_**

**Comment by dangalv** [comment]
@amargedon

**Comment by amargedon** [comment]
I understand the request, and have seen this platform as well.

However, there is only a trail account for 7 days after which payment is required. This would make testing these scripts (initial and later on for support) difficult since I do not use gainium. 

Secondly, the api does not offer a lot of endpoints yet. And the endpoints currently offered do not offer a lot of options. For example updating the pairs of a bot is not possible, or fetching DCA settings for trailing safety orders.

So given these points, I don't see an update working with gainium in the near future happening.

**Comment by dangalv** [comment]
> I understand the request, and have seen this platform as well.
> 
> However, there is only a trail account for 7 days after which payment is required. This would make testing these scripts (initial and later on for support) difficult since I do not use gainium.
> 
> Secondly, the api does not offer a lot of endpoints yet. And the endpoints currently offered do not offer a lot of options. For example updating the pairs of a bot is not possible, or fetching DCA settings for trailing safety orders.
> 
> So given these points, I don't see an update working with gainium in the near future happening.

Hey Amargedon!
Thank you for your response, I didn't know I had so many obstacles, surely because it is a fairly new platform it is still green in some things, if I can talk to the Gainium staff and they give me an answer I will tell you anything. The platform has potential

**Comment by amargedon** [comment]
I wouldn't deny there is potential in Gainium, from what I've seen it looks good and offers already a lot of features. It's only on the API side not yet extened enough. And even then, what I said about the option to test and maintain these scripts in the longer future would be a challange given the current subscription structure. 

I can also imagine the creator (or people behind) of Gainium do want to implement these features in Gainium itself, but I don't know. 

And something else that came up in my mind; the datastructures used in the scripts are directly connected to 3Commas. It would mean we need to implement an abstraction layer to make sure the scripts are using data in such a way I doesn't matter if it comes from 3C or Gainium. Not saying it's nog possible, but also not something fixed in a hour.

**Comment by dangalv** [comment]
> I wouldn't deny there is potential in Gainium, from what I've seen it looks good and offers already a lot of features. It's only on the API side not yet extened enough. And even then, what I said about the option to test and maintain these scripts in the longer future would be a challange given the current subscription structure.
> 
> I can also imagine the creator (or people behind) of Gainium do want to implement these features in Gainium itself, but I don't know.
> 
> And something else that came up in my mind; the datastructures used in the scripts are directly connected to 3Commas. It would mean we need to implement an abstraction layer to make sure the scripts are using data in such a way I doesn't matter if it comes from 3C or Gainium. Not saying it's nog possible, but also not something fixed in a hour.

He just told me something similar to what you mentioned and I paraphrase some of what he told me is that "the API endpoints offered are basic due to lack of users. Although it would be easy to add an endpoint to modify peers, they lack functionality for DCA tracking. Additionally, adding a new platform would involve an abstraction layer, and the effort required might not be justified, considering that 3commas is considerably larger than Gainium. It is suggested that perhaps in the future these improvements make more sense."
We'll have to wait :(
Anyway, thanks for your willingness, I'll let you know any news!
Greetings

**Comment by amargedon** [comment]
Thanks for checking with Gainium as well! For now I will close this issue.
