### ISSUE TITLE
Integrate Coinmarketcap API

### ISSUE THREAD

**Issue by pikespeak** [cyberjunky/3commas-cyber-bots#20]
How about integrating the API of Coinmarketcap. Then you could filter the cryptocoin pairs by additional criteria like market cap or trading volume.

**Comment by cyberjunky** [comment]
What exactly do you want to do with Coinmarketcap data then?

The 24hr trading volume is already taken into account when selecting pairs, if you have set one in your bot(s)
And Lunarcrush GalaxyScore and AltRank scores also look at market cap 
So it looks redundant, missing the point of using LC data.

https://lunarcrush.com/faq/what-metrics-are-available-on-lunarcrush

**Comment by amargedon** [comment]
Ha ok, reading this after the script has been created. I've been working on this over the past days and currently the script is in a branch. I have it running for the next days in order to test and see what pops up...don't expect anything so can finish it up next week or so.

Currently the script will get the top x coins (configurable number) from CMC, sorted on market cap. No other selection(s) are currently in.

**Comment by cyberjunky** [comment]
@amargedon I think you need to fetch more data from CMC, maybe 100 (if amount of data is reasonable) to have enough pairs left to fill 'numberofpairs'. if some of them happen to be on blacklist, or not in marketdata and are skipped.
