### ISSUE TITLE
Add configuration option for log/notification level

### ISSUE THREAD

**Issue by pvdochtend** [cyberjunky/3commas-cyber-bots#88]
**Describe the solution you'd like**
It would be nice if you can configure the level of notification and level of logging separatly.

I currently use the altrank script to update every 10 minutes but my Telegram get's flooded then. I am only interested if a bot updated fails. So only when the error occurs. Then I probably need to take action.

The logging on the server (in the logging file) I want to have in a different level so I can look back what happens.

My suggestion:

Two parameters in the ini:

LoggingLevel
NotificationLevel

Levels are (If I check the current logging function) (in order of display information)

(NONE) optional
INFO
WARNING
ERROR
DEBUG

**Describe alternatives you've considered**
I tried to modify the scripts myself. But I find the logging function to have multiple purposes. Notification is also there and that functionality should be separated in my opinion to have the concept working independently.

**Comment by meizenga** [comment]
I concur. I would like to have the option to enable/disabled or select the notifications.

------------------------------------------------------------------------------
This is the notification I would like to disable since I see no point of having a notification for this:

botname, [14-3-2022 21:41]
[3C Cyber Bot-Helper tpincrement]

Next update in 300 Seconds at 21:46:40
------------------------------------------------------------------------------
These are the notifications I want to see:
botname, [14-3-2022 18:06]
[3C Cyber Bot-Helper tpincrement]

Incremented TP for deal 123456789/BUSD_MBOX and bot "botname"
Changed TP from 2.5% to 2.7% (+0.2%)

**Comment by cyberjunky** [comment]
But this info "Next update in 300 Seconds at 21:46:40" doesn't fit under 'warning' nor under 'error', so we could just move it to debug, we have nothing between info and debug levels anyway... Or group them more, and only post them if there is something useful to mention.

**Comment by meizenga** [comment]
Agree. This is basically the only info I'm interested in:
Incremented TP for deal 123456789/BUSD_MBOX and bot "botname"
Changed TP from 2.5% to 2.7% (+0.2%)

**Comment by cyberjunky** [comment]
I have removed the notifies about next update interval.
