### ISSUE TITLE
Unknown error occurred#Exceptions::OpenDealPresentForThisPair None None

### ISSUE THREAD

**Issue by qbixx** [cyberjunky/3commas-cyber-bots#9]
After running the watchlist.py script for a few days, the following errors sometimes shows up in the logs:

`Error occurred while triggering start_new_deal bot 'Bot name' error: Other error occurred: Unknown error occurred#Exceptions::OpenDealPresentForThisPair None None.`

Most of the time, the corresponding coin is added to 3commas, but i've also seen instances where the coin didn't got added.

**Comment by cyberjunky** [comment]
Hi thanks for reporting, was this while running test on a paper trade bot by any chance?

**Comment by qbixx** [comment]
Yes, the script is currently running on a paper trade bot.

**Comment by cyberjunky** [comment]
This is normal behavior for a paper trading bot, because the exchange in the messages are then being ignored, so when you get same pair for BINANCE and KUCOIN right after each other they both get mapped to your Paper exchange. It could be that 3C is still working on the first action, question is does it fail altogether when you trigger 2 within 1-2 seconds. Can you check next time this happens?

**Comment by qbixx** [comment]
When looking back in the log, this indeed seems to be the case. Only when the same coin on multiple exchanges is added, the message appears. When the coin is added to one exchange, the message doesn't appear.

So it seems indeed to be related only to paper trade bots and one coin on multiple exchanges.

Will close this issue, thanks for you help!

**Comment by cyberjunky** [comment]
I will write this in the FAQ, I also noticed this once, but your issue made me find the reason, thanks.
