### ISSUE TITLE
Add close deal command on watchlist

### ISSUE THREAD

**Issue by Zmizo** [cyberjunky/3commas-cyber-bots#95]
Hi , 

it will be great if you can add close deal function to the watchlist file 

so when we want to close a deal we would use 

BINANCE
#USDT_ATOM
LONG
CLOSE

**Comment by cyberjunky** [comment]
I have added support for it to latest code, please test!
It will check in runtime for open deals for the bot(s) when close command is received, and check if there is an active deal for the specific pair, since it can already be closed otherwise. (in that case it does nothing besides displaying a log entry)

This means if you run more than 1 bot with watchlist script all deals *for that pair* will be closed.

These will work:

```
BINANCE
#USDT_ATOM
LONG
CLOSE
```

```
BINANCE
#USDT_ATOM
CLOSE
```
